services:
  tecmarket-app:
    build: ./TecMarket
    ports:
      - "8080:8080"
    environment:
      DB_URL:   jdbc:mysql://tecmarket-db:3306/tecmarket?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME:  root
      DB_PASSWORD:  12345
    depends_on:
      tecmarket-db:
        condition: service_healthy
    restart: always

  tecmarket-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: tecmarket
    ports:
      - "3307:3306"
    volumes:
      - tecmarket_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always

volumes:
  tecmarket_data:
